# Generated by Django 3.0.3 on 2020-03-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(default='tiguo')),
                ('start_time', models.TextField(default='0')),
                ('road_type', models.CharField(db_index=True, default='', max_length=25)),
                ('gps_lag', models.FloatField(db_index=True, default=0)),
                ('gps_long', models.FloatField(db_index=True, default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('car', models.IntegerField(db_index=True, default=0)),
                ('bike', models.IntegerField(db_index=True, default=0)),
                ('man', models.IntegerField(db_index=True, default=0)),
            ],
        ),
    ]
