# Generated by Django 3.0.3 on 2020-03-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='bike',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='frame',
            name='car',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='frame',
            name='gps_lag',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='frame',
            name='gps_long',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='frame',
            name='man',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='frame',
            name='road_type',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
