# Generated by Django 3.0.3 on 2020-03-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200306_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='road_type',
            field=models.CharField(db_index=True, default='', max_length=25),
        ),
    ]
